pipeline {
  agent any
  triggers { upstream(upstreamProjects: 'mlp-build-all', threshold: hudson.model.Result.SUCCESS) }

  stages {
    stage('build svc-app-1') {
      steps {
        sh 'echo "build-app-1"'
      }
    }
    stage('test') {
      parallel {
        stage('test') {
          steps {
            sh 'echo "performance test"'
          }
        }
        stage('reg') {
          steps {
            sh 'echo "regression test"'
          }
        }

        stage('sec') {
          steps {
            sh 'echo "security checks test"'
          }
        }
 
      }
    }
  }
}
